name: Install Ansible and Terraform on Debian

on:
  workflow_dispatch:  # Manual trigger

jobs:
  setup:
    name: Install Tools
    runs-on: self-hosted

    steps:
      - name: Update Package Index
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl gnupg lsb-release python3-pip

      - name: Install Ansible (via pip - Debian safe)
        run: |
          pip3 install ansible
          ansible --version

      - name: Install Terraform (official HashiCorp repo)
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | \
            sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
            https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt-get update -y
          sudo apt-get install -y terraform
          terraform -version
