- name: Install Ansible & dependencies
  run: |
    python3 -m venv venv
    source venv/bin/activate
    pip install ansible google-auth google-api-python-client
    ansible-galaxy collection install google.cloud

- name: Set up files
  run: |
    echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcp-service-account.json

    cat <<EOF > gcp_inventory.yml
    plugin: gcp_compute
    projects:
      - galvanic-flame-466111-q8
    zones:
      - us-central1-c
    auth_kind: serviceaccount
    service_account_file: gcp-service-account.json
    hostnames:
      - name
    EOF

    cat <<EOF > ansible.cfg
    [defaults]
    inventory = ./gcp_inventory.yml
    host_key_checking = False

    [inventory]
    enable_plugins = gcp_compute
    EOF

- name: Run Ansible playbook
  run: |
    source venv/bin/activate
    ansible-inventory -i gcp_inventory.yml --graph
    ansible-playbook -i gcp_inventory.yml playbook.yml

