name: Run Ansible with GCP Dynamic Inventory

on:
  workflow_dispatch:

jobs:
  ansible-gcp:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install ansible
          pip install google-auth google-api-python-client
          ansible-galaxy collection install google.cloud

      - name: Write GCP service account file
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > gcp-service-account.json

      - name: Run Ansible playbook with GCP dynamic inventory
        run: |
          source venv/bin/activate
          ansible-playbook -i gcp_inventory.yml playbook.yml

